### ISSUE TITLE
Sudėti linkus ant rėmėjų ir draugų logo

### ISSUE THREAD

**Issue by kuusas** [ntacamp/2015.notrollsallowed.com#13]
Sudėti linkus ant rėmėjų ir draugų logotipų

**Comment by Pawka** [comment]
+ sudėt draugus: Rikis, Kaunas Makerspace, Technarium, jpg.lt

**Comment by podolskis** [comment]
Draugas foosin?

**Comment by Pawka** [comment]
Taip.

**Comment by podolskis** [comment]
@Pawka, paderink jpg.lt geresnės kokybės logo. Kitus sudėjau.

**Comment by Pawka** [comment]
Sumesk dabar tuos, kurie yra. Kai duos logo - įkelsim.
