### ISSUE TITLE
Pašalinti nereikalingus laukus iš registracijos formos

### ISSUE THREAD

**Issue by Pawka** [ntacamp/2015.notrollsallowed.com#14]
Pranešimo registracijos forma turi vartotojo profilio formą savyje. Bet registracijoj papildomi laukai, kaip Twitter, Github, Facebook yra nereikalingi. Reikia juos pašalinti.

**Comment by kuusas** [comment]
Jeigu pašalinsim, niekas jų neužpildys.

**Comment by Pawka** [comment]
Geriau tegul neužpildo, negu pateikt juos prie pranešimo registracijos. Registracija turi būti kaip įmanoma paprastesnė. Tuo labiau, kad dabar neaišku kurie laukai privalomi, o kurie ne.

**Comment by kuusas** [comment]
Tai gal geriau padizainint formą. Pvz. išskirt į du stulpelius pranešimo info ir userio info, ir pažymėt privalomus laukus.

**Comment by Pawka** [comment]
Ten yra pranešimo registracijos forma.
Perteklinė informacija yra nereikalinga :-)
Jei useriai nesusives savo informacijos - nieko tokio. Bet galėsim jiems tai pasiūlyti padaryti per newsletterius ar FB.

**Comment by kuusas** [comment]
Ok ;) Tada feature sugalvojau - prisijungusiam rodyti kiek % jo profilis yra "complete" :)

**Comment by Pawka** [comment]
Apie tai irgi galvojau, bet čia gal kaip papildomą funkciją. Nebent labai norėsi padaryt :-)

**Comment by kuusas** [comment]
Žinoma, kaip papildomą ;)  https://github.com/ntacamp/2015.notrollsallowed.com/issues/15
