### ISSUE TITLE
Neleisti vartotojams keisti track'o

### ISSUE THREAD

**Issue by Pawka** [ntacamp/2015.notrollsallowed.com#8]
Vartotojai neturėtų keisti pranešimo track'o. Kartais būna, kad užregistruotas pranešimas neatitinka scenos. Tokiu atveju administratoriai gali pataisyti pranešimą ir perkelti jį į reikiamą sceną.

Tačiau jei vartotojas vėl perkels pranešimą atgal - administratoriai gali to nepastebėti.

**Comment by kuusas** [comment]
Pasiimu sutvarkyt.
