### ISSUE TITLE
Pranešimų atvaizdavimo bugai

### ISSUE THREAD

**Issue by Pawka** [ntacamp/2015.notrollsallowed.com#9]
- Pranešimų sąraše labiau išryškinti temą, o ne autorių. Dabar į akis krenta autoriaus galva ir kas jis toks.   O temos pavadinimas nublanksta. Taip negerai.
- Pranešimo puslapyje sutvarkyti robohash avataro dydį. Tkriausiai su CSS, kad būtų kešuojami tie patys paveiksliukai kaip ir sąraše. Be to Gravatar'as klaidingai nukreipia užklausą.

**Comment by kuusas** [comment]
Sutvarkysiu šitus.
